-- Initial cleanup block to safely remove existing objects and prevent ORA-00955 errors
BEGIN
  FOR cur_rec IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'COMPLAINT_ASSIGNMENTS', 'NOTIFICATIONS', 'STAFF_HIERARCHY', 'COMPLAINT_LOGS', 
    'ATTACHMENTS', 'COMPLAINTS', 'COMPLAINT_RESOLUTION_STATS', 'COMPLAINT_CATEGORIES', 
    'DEPARTMENTS', 'USERS')) 
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- 1_create_schema.sql
-- Updated Schema: adds urgent flag, expected/actual resolution minutes, assignments, and resolution stats

-- Users table
CREATE TABLE users (
  user_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(100) UNIQUE NOT NULL,
  full_name     VARCHAR2(200),
  role          VARCHAR2(20) NOT NULL CHECK (role IN ('STUDENT','STAFF','ADMIN')),
  email         VARCHAR2(200),
  department_id NUMBER,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Departments
CREATE TABLE departments (
  department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(200) NOT NULL
);

-- Complaint categories with SLA in hours
CREATE TABLE complaint_categories (
  category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(200) NOT NULL,
  sla_hours   NUMBER DEFAULT 48 -- default SLA 48 hours
);

-- Complaints (extended)
CREATE TABLE complaints (
  complaint_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  complaint_no                VARCHAR2(50) UNIQUE,
  student_id                  NUMBER NOT NULL,
  category_id                 NUMBER NOT NULL,
  department_id               NUMBER,
  description                 CLOB,
  created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP,
  status                      VARCHAR2(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','ESCALATED','CLOSED')),
  assigned_staff_id           NUMBER,
  escalation_level            NUMBER DEFAULT 1,
  sla_deadline                TIMESTAMP,
  resolution_attachment_id    NUMBER,
  closed_at                   TIMESTAMP,
  -- New: urgent indicator (1 = urgent)
  urgent_flag                 NUMBER(1) DEFAULT 0,
  -- New: expected resolution estimate in minutes (derived from SLA/category/history/urgent)
  expected_resolution_minutes NUMBER,
  -- New: actual time taken in minutes (stored when resolved)
  resolution_minutes          NUMBER,
  CONSTRAINT fk_c_student FOREIGN KEY (student_id) REFERENCES users(user_id),
  CONSTRAINT fk_c_category FOREIGN KEY (category_id) REFERENCES complaint_categories(category_id),
  CONSTRAINT fk_c_dept FOREIGN KEY (department_id) REFERENCES departments(department_id),
  CONSTRAINT fk_c_assigned FOREIGN KEY (assigned_staff_id) REFERENCES users(user_id)
);

-- Attachments
CREATE TABLE attachments (
  attachment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  complaint_id  NUMBER,
  filename      VARCHAR2(255),
  content_type  VARCHAR2(100),
  content_blob  BLOB,
  is_resolution NUMBER(1) DEFAULT 0, -- 1 means it's proof of resolution
  uploaded_by   NUMBER,
  uploaded_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_a_complaint FOREIGN KEY (complaint_id) REFERENCES complaints(complaint_id) ON DELETE CASCADE,
  CONSTRAINT fk_a_uploader FOREIGN KEY (uploaded_by) REFERENCES users(user_id)
);

-- Complaint logs for audit/history
CREATE TABLE complaint_logs (
  log_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  complaint_id  NUMBER NOT NULL,
  log_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
  actor_user_id NUMBER,
  action        VARCHAR2(100),
  details       CLOB,
  CONSTRAINT fk_log_complaint FOREIGN KEY (complaint_id) REFERENCES complaints(complaint_id)
);

-- Staff hierarchy mapping staff -> manager
CREATE TABLE staff_hierarchy (
  staff_id        NUMBER PRIMARY KEY,
  manager_id      NUMBER,
  hierarchy_level NUMBER DEFAULT 1,
  CONSTRAINT fk_sh_staff FOREIGN KEY (staff_id) REFERENCES users(user_id),
  CONSTRAINT fk_sh_manager FOREIGN KEY (manager_id) REFERENCES users(user_id)
);

-- Notifications
CREATE TABLE notifications (
  notification_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id         NUMBER,
  complaint_id    NUMBER,
  notif_type      VARCHAR2(50),
  payload         CLOB,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
  read_flag       NUMBER(1) DEFAULT 0,
  CONSTRAINT fk_n_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_n_complaint FOREIGN KEY (complaint_id) REFERENCES complaints(complaint_id)
);

-- New: assignment/queue table tracks assignment events and queue position per worker
CREATE TABLE complaint_assignments (
  assignment_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  complaint_id      NUMBER NOT NULL,
  staff_id          NUMBER NOT NULL,
  assigned_by       NUMBER,
  assigned_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
  queue_position    NUMBER NOT NULL,
  active_assignment NUMBER(1) DEFAULT 1, -- 1 = current active assignment for complaint
  CONSTRAINT fk_ca_complaint FOREIGN KEY (complaint_id) REFERENCES complaints(complaint_id) ON DELETE CASCADE,
  CONSTRAINT fk_ca_staff FOREIGN KEY (staff_id) REFERENCES users(user_id),
  CONSTRAINT fk_ca_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(user_id)
);

-- New: resolution statistics (averages) to compute expected timelines from history
CREATE TABLE complaint_resolution_stats (
  stats_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  category_id     NUMBER NOT NULL,
  worker_id       NUMBER, -- nullable: NULL means aggregated across workers for category
  avg_minutes     NUMBER DEFAULT 0,
  resolved_count  NUMBER DEFAULT 0,
  last_updated    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_crs_category FOREIGN KEY (category_id) REFERENCES complaint_categories(category_id),
  CONSTRAINT fk_crs_worker FOREIGN KEY (worker_id) REFERENCES users(user_id)
);

-- Helper indexes
CREATE INDEX ix_complaints_student_id ON complaints(student_id);
CREATE INDEX ix_complaints_status_deadline ON complaints(status, sla_deadline);
CREATE INDEX ix_attachments_complaint_id ON attachments(complaint_id);
CREATE INDEX ix_ca_staff_pos ON complaint_assignments(staff_id, queue_position);
CREATE INDEX ix_crs_category_worker ON complaint_resolution_stats(category_id, worker_id);
/

-- 2_grievance_pkg_spec.sql
-- Updated Package specification with urgent support, queue view, and manager query

CREATE OR REPLACE PACKAGE grievance_pkg IS
  -- Exceptions
  e_not_authorized EXCEPTION;
  e_missing_resolution_proof EXCEPTION;
  e_not_found EXCEPTION;

  -- Create a complaint; returns complaint_id
  -- p_urgent: 1 => urgent; 0 => normal
  FUNCTION create_complaint(
    p_student_id    IN NUMBER,
    p_category_id   IN NUMBER,
    p_department_id IN NUMBER,
    p_description   IN CLOB,
    p_urgent        IN NUMBER DEFAULT 0
  ) RETURN NUMBER;

  -- Attach binary to complaint (simple separate call)
  FUNCTION add_attachment(
    p_complaint_id  IN NUMBER,
    p_filename      IN VARCHAR2,
    p_content_type  IN VARCHAR2,
    p_blob          IN BLOB,
    p_uploaded_by   IN NUMBER,
    p_is_resolution IN NUMBER DEFAULT 0
  ) RETURN NUMBER;

  -- Assign complaint to staff (now tracks queue position)
  PROCEDURE assign_complaint(
    p_complaint_id IN NUMBER,
    p_staff_id     IN NUMBER,
    p_assigned_by  IN NUMBER
  );

  -- Mark complaint resolved; requires an attachment id as proof OR existing resolution attachment
  PROCEDURE resolve_complaint(
    p_complaint_id             IN NUMBER,
    p_resolver_id              IN NUMBER,
    p_resolution_attachment_id IN NUMBER
  );

  -- Safe delete: students can delete their own complaint; staff can delete only if resolution proof exists
  PROCEDURE delete_complaint(
    p_complaint_id IN NUMBER,
    p_requester_id IN NUMBER
  );

  -- Escalation routine: escalate overdue complaints (intended to be called by scheduler)
  PROCEDURE escalate_due_complaints;

  -- Utility: get complaint status (returns status)
  FUNCTION get_status(p_complaint_id IN NUMBER) RETURN VARCHAR2;

  -- Return active complaints under a manager (includes those assigned to anyone reporting to the manager)
  -- Returns a SYS_REFCURSOR that the caller can FETCH from
  FUNCTION get_active_complaints_under_manager(p_manager_id IN NUMBER) RETURN SYS_REFCURSOR;
END grievance_pkg;
/

-- 3_grievance_pkg_body.sql
-- Updated implementation: urgent handling, queueing, resolution stats, manager view

CREATE OR REPLACE PACKAGE BODY grievance_pkg IS

  /* helper to compute SLA deadline from category.sla_hours,
     and apply urgent reduction if needed. Returns deadline TIMESTAMP and expected_minutes */
  PROCEDURE compute_deadline_and_expected(
    p_created_at IN TIMESTAMP,
    p_sla_hours  IN NUMBER,
    p_urgent     IN NUMBER,
    o_deadline   OUT TIMESTAMP,
    o_expected_minutes OUT NUMBER
  ) IS
    l_hours NUMBER := NVL(p_sla_hours, 48);
    l_effective_hours NUMBER;
  BEGIN
    IF p_urgent = 1 THEN
      -- For urgent, reduce expected time. Strategy:
      -- If history exists (handled later), we will override expected_minutes.
      -- Default urgent fallback: half the SLA but at least 1 hour.
      l_effective_hours := GREATEST(1, FLOOR(l_hours / 2));
    ELSE
      l_effective_hours := l_hours;
    END IF;

    o_deadline := p_created_at + NUMTODSINTERVAL(l_effective_hours, 'HOUR');
    o_expected_minutes := l_effective_hours * 60;
  END compute_deadline_and_expected;

  /* helper to compute minutes difference */
  FUNCTION minutes_between(p_start TIMESTAMP, p_end TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN ROUND((CAST(p_end AS DATE) - CAST(p_start AS DATE)) * 24 * 60); -- date arithmetic: days -> minutes
  END minutes_between;

  FUNCTION create_complaint(
    p_student_id    IN NUMBER,
    p_category_id   IN NUMBER,
    p_department_id IN NUMBER,
    p_description   IN CLOB,
    p_urgent        IN NUMBER DEFAULT 0
  ) RETURN NUMBER IS
    l_id NUMBER;
    l_created_at TIMESTAMP := SYSTIMESTAMP;
    l_sla_hours NUMBER;
    l_deadline TIMESTAMP;
    l_expected_minutes NUMBER;
    l_historical_avg NUMBER;
  BEGIN
    SELECT sla_hours INTO l_sla_hours FROM complaint_categories WHERE category_id = p_category_id;

    -- baseline deadline & expected minutes
    compute_deadline_and_expected(l_created_at, l_sla_hours, p_urgent, l_deadline, l_expected_minutes);

    INSERT INTO complaints (student_id, category_id, department_id, description, created_at, sla_deadline, urgent_flag, expected_resolution_minutes)
    VALUES (p_student_id, p_category_id, p_department_id, p_description, l_created_at, l_deadline, p_urgent, l_expected_minutes)
    RETURNING complaint_id INTO l_id;

    -- set complaint_no using created date + id
    UPDATE complaints
      SET complaint_no = 'CMP' || TO_CHAR(l_created_at, 'YYYYMMDD') || LPAD(l_id, 6, '0')
    WHERE complaint_id = l_id;

    -- If urgent, try to refine expected_resolution_minutes from history across this category (worker-agnostic)
    IF p_urgent = 1 THEN
      BEGIN
        SELECT avg_minutes INTO l_historical_avg
        FROM complaint_resolution_stats
        WHERE category_id = p_category_id AND worker_id IS NULL;
        -- if historical found, use a more aggressive expected: min(historical, current expected) * 0.7 (faster for urgent)
        l_expected_minutes := LEAST(NVL(l_historical_avg, l_expected_minutes), l_expected_minutes) * 0.7;
        -- update both expected and sla_deadline accordingly
        UPDATE complaints
          SET expected_resolution_minutes = ROUND(l_expected_minutes),
              sla_deadline = l_created_at + NUMTODSINTERVAL(ROUND(l_expected_minutes)/60,'HOUR')
          WHERE complaint_id = l_id;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        NULL;
      END;
    END IF;

    -- log
    INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
      VALUES (l_id, p_student_id, 'CREATE', 'Complaint created' || CASE WHEN p_urgent = 1 THEN ' (URGENT)' ELSE '' END);

    RETURN l_id;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20001, 'Unknown category_id');
  END create_complaint;

  FUNCTION add_attachment(
    p_complaint_id  IN NUMBER,
    p_filename      IN VARCHAR2,
    p_content_type  IN VARCHAR2,
    p_blob          IN BLOB,
    p_uploaded_by   IN NUMBER,
    p_is_resolution IN NUMBER DEFAULT 0
  ) RETURN NUMBER IS
    l_id NUMBER;
  BEGIN
    INSERT INTO attachments(complaint_id, filename, content_type, content_blob, is_resolution, uploaded_by)
    VALUES(p_complaint_id, p_filename, p_content_type, p_blob, p_is_resolution, p_uploaded_by)
    RETURNING attachment_id INTO l_id;

    INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
      VALUES (p_complaint_id, p_uploaded_by, 'ATTACH', 'Attachment ' || p_filename || (CASE WHEN p_is_resolution = 1 THEN ' (RESOLUTION)' ELSE '' END));

    IF p_is_resolution = 1 THEN
      -- optionally set as resolution_attachment_id on complaint
      UPDATE complaints SET resolution_attachment_id = l_id WHERE complaint_id = p_complaint_id;
    END IF;

    RETURN l_id;
  END add_attachment;

  PROCEDURE assign_complaint(
    p_complaint_id IN NUMBER,
    p_staff_id     IN NUMBER,
    p_assigned_by  IN NUMBER
  ) IS
    l_max_pos NUMBER;
  BEGIN
    -- Set active_assignment = 0 for previous assignments for this complaint
    UPDATE complaint_assignments SET active_assignment = 0 WHERE complaint_id = p_complaint_id AND active_assignment = 1;

    -- determine queue position for this staff (next)
    SELECT NVL(MAX(queue_position),0) + 1 INTO l_max_pos FROM complaint_assignments WHERE staff_id = p_staff_id;

    -- insert a new assignment row (historic + queue position)
    INSERT INTO complaint_assignments (complaint_id, staff_id, assigned_by, queue_position, active_assignment)
      VALUES (p_complaint_id, p_staff_id, p_assigned_by, l_max_pos, 1);

    -- update complaints table to point to current assigned staff and set status
    UPDATE complaints
      SET assigned_staff_id = p_staff_id,
          status = 'IN_PROGRESS'
      WHERE complaint_id = p_complaint_id;

    IF SQL%ROWCOUNT = 0 THEN RAISE e_not_found; END IF;

    INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
      VALUES (p_complaint_id, p_assigned_by, 'ASSIGN', 'Assigned to staff id ' || p_staff_id || ' pos=' || l_max_pos);

    -- notify the assigned staff
    INSERT INTO notifications (user_id, complaint_id, notif_type, payload)
      VALUES (p_staff_id, p_complaint_id, 'ASSIGNED', 'Assigned by ' || p_assigned_by || ' queue_pos=' || l_max_pos);
  END assign_complaint;

  PROCEDURE resolve_complaint(
    p_complaint_id             IN NUMBER,
    p_resolver_id              IN NUMBER,
    p_resolution_attachment_id IN NUMBER
  ) IS
    l_has_resolution NUMBER := 0;
    l_created TIMESTAMP;
    l_closed TIMESTAMP := SYSTIMESTAMP;
    l_minutes NUMBER;
    l_category NUMBER;
    l_worker NUMBER;
    l_cnt NUMBER;
  BEGIN
    -- require resolution attachment either passed or already on complaint
    IF p_resolution_attachment_id IS NOT NULL THEN
      SELECT COUNT(*) INTO l_has_resolution FROM attachments WHERE attachment_id = p_resolution_attachment_id AND is_resolution = 1;
      IF l_has_resolution = 0 THEN
        -- mark it as resolution if exists
        UPDATE attachments SET is_resolution = 1 WHERE attachment_id = p_resolution_attachment_id;
      END IF;
    END IF;

    SELECT COUNT(*) INTO l_has_resolution FROM attachments WHERE complaint_id = p_complaint_id AND is_resolution = 1;

    IF l_has_resolution = 0 THEN
      RAISE_APPLICATION_ERROR(-20002, 'A resolution proof attachment (is_resolution=1) is required to resolve the complaint.');
    END IF;

    -- fetch created_at and category for stats calculation
    SELECT created_at, category_id, assigned_staff_id
      INTO l_created, l_category, l_worker
      FROM complaints
      WHERE complaint_id = p_complaint_id;

    -- calculate actual minutes taken
    l_minutes := minutes_between(l_created, l_closed);

    -- update complaint with resolved state and resolution minutes
    UPDATE complaints
      SET status = 'RESOLVED',
          closed_at = l_closed,
          resolution_attachment_id = NVL(p_resolution_attachment_id, resolution_attachment_id),
          resolution_minutes = l_minutes
      WHERE complaint_id = p_complaint_id;

    INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
      VALUES (p_complaint_id, p_resolver_id, 'RESOLVE', 'Marked as resolved, minutes=' || l_minutes);

    -- Safe stats UPSERT to avoid any ORA-00984 issues
    BEGIN
      IF l_worker IS NOT NULL THEN
        SELECT COUNT(*) INTO l_cnt FROM complaint_resolution_stats WHERE category_id = l_category AND worker_id = l_worker;
        IF l_cnt > 0 THEN
          UPDATE complaint_resolution_stats
          SET avg_minutes = ROUND((NVL(avg_minutes, 0) * NVL(resolved_count, 0) + l_minutes) / (NVL(resolved_count, 0) + 1), 2),
              resolved_count = NVL(resolved_count, 0) + 1,
              last_updated = SYSTIMESTAMP
          WHERE category_id = l_category AND worker_id = l_worker;
        ELSE
          INSERT INTO complaint_resolution_stats (category_id, worker_id, avg_minutes, resolved_count, last_updated)
          VALUES (l_category, l_worker, l_minutes, 1, SYSTIMESTAMP);
        END IF;
      END IF;

      SELECT COUNT(*) INTO l_cnt FROM complaint_resolution_stats WHERE category_id = l_category AND worker_id IS NULL;
      IF l_cnt > 0 THEN
        UPDATE complaint_resolution_stats
        SET avg_minutes = ROUND((NVL(avg_minutes, 0) * NVL(resolved_count, 0) + l_minutes) / (NVL(resolved_count, 0) + 1), 2),
            resolved_count = NVL(resolved_count, 0) + 1,
            last_updated = SYSTIMESTAMP
        WHERE category_id = l_category AND worker_id IS NULL;
      ELSE
        INSERT INTO complaint_resolution_stats (category_id, worker_id, avg_minutes, resolved_count, last_updated)
        VALUES (l_category, NULL, l_minutes, 1, SYSTIMESTAMP);
      END IF;
    EXCEPTION WHEN OTHERS THEN
          DECLARE
            l_err_msg VARCHAR2(4000) := SQLERRM;
          BEGIN
            INSERT INTO complaint_logs (complaint_id, action, details) 
            VALUES (p_complaint_id, 'STATS_UPDATE_FAIL', l_err_msg);
          END;
        END;

    -- notify original student and assigned staff
    DECLARE
      l_student users.user_id%TYPE;
    BEGIN
      SELECT student_id INTO l_student FROM complaints WHERE complaint_id = p_complaint_id;
      INSERT INTO notifications (user_id, complaint_id, notif_type, payload)
        VALUES (l_student, p_complaint_id, 'RESOLVED', 'Resolved by ' || p_resolver_id || ' minutes=' || l_minutes);
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
    END;

    -- mark any active assignments inactive
    UPDATE complaint_assignments SET active_assignment = 0 WHERE complaint_id = p_complaint_id AND active_assignment = 1;
  END resolve_complaint;

  PROCEDURE delete_complaint(
    p_complaint_id IN NUMBER,
    p_requester_id IN NUMBER
  ) IS
    l_role VARCHAR2(20);
    l_owner NUMBER;
    l_has_resolution NUMBER;
  BEGIN
    SELECT role INTO l_role FROM users WHERE user_id = p_requester_id;
    SELECT student_id INTO l_owner FROM complaints WHERE complaint_id = p_complaint_id;

    IF l_role = 'STUDENT' THEN
      IF l_owner != p_requester_id THEN
        RAISE_APPLICATION_ERROR(-20003, 'Student may only delete their own complaint.');
      END IF;
      -- allow delete
      DELETE FROM complaints WHERE complaint_id = p_complaint_id;
      INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
        VALUES (p_complaint_id, p_requester_id, 'DELETE', 'Deleted by student');
    ELSIF l_role = 'STAFF' OR l_role = 'ADMIN' THEN
      -- staff can delete only if there is resolution proof
      SELECT COUNT(*) INTO l_has_resolution FROM attachments WHERE complaint_id = p_complaint_id AND is_resolution = 1;
      IF l_has_resolution = 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Staff may not delete a complaint unless a resolution proof attachment exists.');
      END IF;
      DELETE FROM complaints WHERE complaint_id = p_complaint_id;
      INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
        VALUES (p_complaint_id, p_requester_id, 'DELETE', 'Deleted by staff/admin');
    ELSE
      RAISE e_not_authorized;
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20005, 'Complaint or user not found.');
  END delete_complaint;

  PROCEDURE escalate_due_complaints IS
    CURSOR c_overdue IS
      SELECT complaint_id, assigned_staff_id, escalation_level
      FROM complaints
      WHERE status IN ('OPEN','IN_PROGRESS')
        AND sla_deadline <= SYSTIMESTAMP;
    l_complaint_id NUMBER;
    l_assigned_staff NUMBER;
    l_level NUMBER;
    l_next_manager NUMBER;
  BEGIN
    FOR r IN c_overdue LOOP
      l_complaint_id := r.complaint_id;
      l_assigned_staff := r.assigned_staff_id;
      l_level := r.escalation_level;

      -- find manager of current assigned staff
      IF l_assigned_staff IS NOT NULL THEN
        SELECT manager_id INTO l_next_manager FROM staff_hierarchy WHERE staff_id = l_assigned_staff;
      ELSE
        -- if unassigned, escalate to department head: find a staff with hierarchy_level = 1 in that department
        BEGIN
          SELECT sh.manager_id INTO l_next_manager
          FROM staff_hierarchy sh
          JOIN complaints c ON c.complaint_id = l_complaint_id
          WHERE sh.hierarchy_level = 1 AND (c.department_id = (SELECT department_id FROM complaints WHERE complaint_id = l_complaint_id) OR sh.manager_id IS NOT NULL)
          FETCH FIRST 1 ROWS ONLY;
        EXCEPTION WHEN NO_DATA_FOUND THEN
          l_next_manager := NULL;
        END;
      END IF;

      -- if manager found, reassign and bump level, mark escalated
      IF l_next_manager IS NOT NULL THEN
        UPDATE complaints
          SET assigned_staff_id = l_next_manager,
              escalation_level = NVL(l_level,1) + 1,
              status = 'ESCALATED',
              sla_deadline = SYSTIMESTAMP + NUMTODSINTERVAL(24, 'HOUR')
          WHERE complaint_id = l_complaint_id;

        INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
          VALUES (l_complaint_id, l_next_manager, 'ESCALATE', 'Auto-escalated to manager ' || l_next_manager);

        INSERT INTO notifications (user_id, complaint_id, notif_type, payload)
          VALUES (l_next_manager, l_complaint_id, 'ESCALATED', 'Auto-escalated');
      ELSE
        -- No manager found: log a notification so admins know
        INSERT INTO complaint_logs (complaint_id, action, details)
          VALUES (l_complaint_id, 'ESCALATE_FAIL', 'No manager found to escalate');
      END IF;
    END LOOP;
  END escalate_due_complaints;

  FUNCTION get_status(p_complaint_id IN NUMBER) RETURN VARCHAR2 IS
    l_status VARCHAR2(20);
  BEGIN
    SELECT status INTO l_status FROM complaints WHERE complaint_id = p_complaint_id;
    RETURN l_status;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE e_not_found;
  END get_status;

  FUNCTION get_active_complaints_under_manager(p_manager_id IN NUMBER) RETURN SYS_REFCURSOR IS
    l_cur SYS_REFCURSOR;
  BEGIN
    OPEN l_cur FOR
      SELECT c.*
      FROM complaints c
      JOIN staff_hierarchy sh ON c.assigned_staff_id = sh.staff_id
      WHERE sh.staff_id IN (
        SELECT staff_id FROM staff_hierarchy
        START WITH manager_id = p_manager_id
        CONNECT BY PRIOR staff_id = manager_id
      )
      AND c.status IN ('OPEN','IN_PROGRESS','ESCALATED');

    RETURN l_cur;
  END get_active_complaints_under_manager;

END grievance_pkg;
/

-- 4_triggers.sql
-- triggers for audit, setting complaint_no, and logging changes

CREATE OR REPLACE TRIGGER trg_complaints_ai
AFTER INSERT ON complaints
FOR EACH ROW
BEGIN
  INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
    VALUES (:NEW.complaint_id, :NEW.student_id, 'INSERT_TRIGGER', 'Inserted complaint via trigger' || CASE WHEN :NEW.urgent_flag = 1 THEN ' (URGENT)' ELSE '' END);
END;
/

CREATE OR REPLACE TRIGGER trg_complaints_au
AFTER UPDATE ON complaints
FOR EACH ROW
DECLARE
  l_details VARCHAR2(4000);
BEGIN
  l_details := 'Status: ' || NVL(:NEW.status,'NULL') || '; Assigned: ' || NVL(TO_CHAR(:NEW.assigned_staff_id),'NULL') || '; ExpectedMin: ' || NVL(TO_CHAR(:NEW.expected_resolution_minutes),'NULL');
  INSERT INTO complaint_logs (complaint_id, actor_user_id, action, details)
    VALUES (:NEW.complaint_id, NVL(:NEW.assigned_staff_id, :NEW.student_id), 'UPDATE', l_details);
END;
/

-- 5_scheduler.sql
-- Create a scheduler job to run escalate_due_complaints every 10 minutes

BEGIN
  DBMS_SCHEDULER.CREATE_JOB (
    job_name        => 'GRIEVANCE_ESCALATION_JOB',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN grievance_pkg.escalate_due_complaints; END;',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=MINUTELY;INTERVAL=10',
    enabled         => TRUE,
    comments        => 'Run escalation routine every 10 minutes'
  );
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -27477 THEN
      DBMS_SCHEDULER.ENABLE('GRIEVANCE_ESCALATION_JOB');
    ELSE
      RAISE;
    END IF;
END;
/